In [1]:
%pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [2]:
import numpy as np

print("=== ДОМАШНЕЕ ЗАДАНИЕ: ДУАЛЬНЫЙ КОД ХЭММИНГА — СИМПЛЕКС ===")

print("1. Генерируем все 7 ненулевых столбцов длины 3 (от 001 до 111):")
columns = []
for i in range(1, 8):
    col = np.array(list(np.binary_repr(i, width=3)), dtype=int)
    columns.append(col)
    print(f"   Столбец {i}: {col}")

H = np.array(columns).T  # 3×7 матрица
print("\n2. Проверочная матрица H кода Хэмминга (7,4):")
print(H)

G = H.copy()
print("\n3. Для кода Хэмминга дуальный код имеет порождающую матрицу G = H")
print("Порождающая матрица дуального кода G (3×7):")
print(G)

n = G.shape[1]  # 7
k = G.shape[0]  # 3
print(f"\n4. Параметры дуального кода: n={n}, k={k}, всего кодовых слов = 2^{k} = {2**k}")

print("\n5. Генерация всех 2^k кодовых слов:")
codewords = []
weights = []

for i in range(2**k):
    u = np.array(list(np.binary_repr(i, width=k)), dtype=int)
    c = (u @ G) % 2
    wt = int(np.sum(c))
    
    codewords.append(c.tolist())
    weights.append(wt)
    
    print(f"   u = {u}  →  c = {c}  (вес Хэмминга = {wt})")

nonzero_weights = [w for w in weights if w > 0]
is_simplex = (len(nonzero_weights) == 7) and all(w == 4 for w in nonzero_weights)

print("\n" + "="*70)
print("6. ИТОГОВАЯ ПРОВЕРКА: ЯВЛЯЕТСЯ ЛИ КОД СИМПЛЕКСОМ?")
print(f"   Все ненулевые кодовые слова имеют вес ровно 4: {is_simplex}")
print(f"   Список ненулевых весов: {sorted(nonzero_weights)}")

if is_simplex:
    print("\nВЫВОД: Дуальный код к коду Хэмминга (7,4) действительно является симплексом [7,3,4].")
else:
    print("\nЧто-то пошло не так (должно быть True).")

=== ДОМАШНЕЕ ЗАДАНИЕ: ДУАЛЬНЫЙ КОД ХЭММИНГА — СИМПЛЕКС ===
1. Генерируем все 7 ненулевых столбцов длины 3 (от 001 до 111):
   Столбец 1: [0 0 1]
   Столбец 2: [0 1 0]
   Столбец 3: [0 1 1]
   Столбец 4: [1 0 0]
   Столбец 5: [1 0 1]
   Столбец 6: [1 1 0]
   Столбец 7: [1 1 1]

2. Проверочная матрица H кода Хэмминга (7,4):
[[0 0 0 1 1 1 1]
 [0 1 1 0 0 1 1]
 [1 0 1 0 1 0 1]]

3. Для кода Хэмминга дуальный код имеет порождающую матрицу G = H
Порождающая матрица дуального кода G (3×7):
[[0 0 0 1 1 1 1]
 [0 1 1 0 0 1 1]
 [1 0 1 0 1 0 1]]

4. Параметры дуального кода: n=7, k=3, всего кодовых слов = 2^3 = 8

5. Генерация всех 2^k кодовых слов:
   u = [0 0 0]  →  c = [0 0 0 0 0 0 0]  (вес Хэмминга = 0)
   u = [0 0 1]  →  c = [1 0 1 0 1 0 1]  (вес Хэмминга = 4)
   u = [0 1 0]  →  c = [0 1 1 0 0 1 1]  (вес Хэмминга = 4)
   u = [0 1 1]  →  c = [1 1 0 0 1 1 0]  (вес Хэмминга = 4)
   u = [1 0 0]  →  c = [0 0 0 1 1 1 1]  (вес Хэмминга = 4)
   u = [1 0 1]  →  c = [1 0 1 1 0 1 0]  (вес Хэмминга = 4)
 